version: "3.8"
services: 
  web: 
    build: .
    ports: 
      - "8080:80"
    links:
      - dbserver
  dbserver:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3000 -w db.json
    ports:
      - "3001:3000"
    volumes:
      - ./data:/data
    restart: always